### ISSUE TITLE
Error: process.stdout cannot be closed.

### ISSUE THREAD

**Issue by inqueue** [tsouza/jp#1]
Mac OS X 10.11.6
node v7.4.0

`jp index/shards` gives output, but ends with this error

```
Error: process.stdout cannot be closed.
    at WriteStream.stdout.destroy.stdout.destroySoon (internal/process/stdio.js:12:18)
    at maybeDestroy (net.js:451:12)
    at WriteStream.Socket.end (net.js:440:5)
    at Object.complete (/usr/local/lib/node_modules/json-processing/dist/lib/output.js:94:20)
    at Object.wrappedComplete (/usr/local/lib/node_modules/json-processing/node_modules/rxjs/Subscriber.js:222:76)
    at SafeSubscriber.__tryOrUnsub (/usr/local/lib/node_modules/json-processing/node_modules/rxjs/Subscriber.js:239:16)
    at SafeSubscriber.complete (/usr/local/lib/node_modules/json-processing/node_modules/rxjs/Subscriber.js:224:26)
    at Subscriber._complete (/usr/local/lib/node_modules/json-processing/node_modules/rxjs/Subscriber.js:133:26)
    at Subscriber.complete (/usr/local/lib/node_modules/json-processing/node_modules/rxjs/Subscriber.js:115:18)
    at MapSubscriber.Subscriber._complete (/usr/local/lib/node_modules/json-processing/node_modules/rxjs/Subscriber.js:133:26)
    at MapSubscriber.Subscriber.complete (/usr/local/lib/node_modules/json-processing/node_modules/rxjs/Subscriber.js:115:18)
    at MergeMapSubscriber.notifyComplete (/usr/local/lib/node_modules/json-processing/node_modules/rxjs/operators/mergeMap.js:167:30)
    at InnerSubscriber._complete (/usr/local/lib/node_modules/json-processing/node_modules/rxjs/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.complete (/usr/local/lib/node_modules/json-processing/node_modules/rxjs/Subscriber.js:115:18)
    at Object.complete (/usr/local/lib/node_modules/json-processing/dist/lib/extensions/rxjs/groupJoin.js:48:39)
    at Object.wrappedComplete (/usr/local/lib/node_modules/json-processing/node_modules/rxjs/Subscriber.js:222:76)
```

**Comment by inqueue** [comment]
I should note the diagnostic was from a large 167 node cluster if it makes a difference.

**Comment by tsouza** [comment]
Fixed. Old project was published to npm.
